
# # Database URL
# spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
# # Database username
# spring.datasource.username=postgres
# # Database password
# spring.datasource.password=12345

# Database URL
spring.datasource.url=jdbc:postgresql://postgres:5432/order_management
# Database username
spring.datasource.username=postgres
# Database password
spring.datasource.password=12345


# # JDBC driver
# spring.datasource.driver-class-name=org.postgresql.Driver
# logging.file.name=app.log

# #jpa
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# #logging levels
# logging.level.root=INFO
# logging.level.org.springframework=WARN
# logging.level.org.hibernate=WARN
# logging.level.com.order_management.demo=DEBUG
# logging.level.org.springframework.security=DEBUG

# #jwt secret key and expiration
# jwt.secret=ThisIsMyVeryLongSecretKeyForJwtGenerationAndValidation123456789
# jwt.expiration=1800000

#redis details
spring.data.redis.host=redis
spring.data.redis.port=6379